//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.18 at 10:45:35 AM EDT 
//


package com.btechconsulting.wein.cumulus.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NewCompound complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewCompound">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ownerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Compound_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Compound" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mwt" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="logp" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="desolv_apolar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="desolv_polar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="hbd" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="hba" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tpsa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="charge" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nrb" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="smiles" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewCompound", propOrder = {
    "ownerID",
    "compoundID",
    "compound",
    "mwt",
    "logp",
    "desolvApolar",
    "desolvPolar",
    "hbd",
    "hba",
    "tpsa",
    "charge",
    "nrb",
    "smiles"
})
@XmlRootElement
public class NewCompound {

    @XmlElement(required = true)
    protected String ownerID;
    @XmlElement(name = "Compound_ID", required = true)
    protected String compoundID;
    @XmlElement(name = "Compound", required = true)
    protected String compound;
    protected Float mwt;
    protected Float logp;
    @XmlElement(name = "desolv_apolar")
    protected Float desolvApolar;
    @XmlElement(name = "desolv_polar")
    protected Float desolvPolar;
    protected Integer hbd;
    protected Integer hba;
    protected Integer tpsa;
    protected Integer charge;
    protected Integer nrb;
    protected String smiles;

    /**
     * Gets the value of the ownerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerID() {
        return ownerID;
    }

    /**
     * Sets the value of the ownerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerID(String value) {
        this.ownerID = value;
    }

    /**
     * Gets the value of the compoundID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompoundID() {
        return compoundID;
    }

    /**
     * Sets the value of the compoundID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompoundID(String value) {
        this.compoundID = value;
    }

    /**
     * Gets the value of the compound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompound() {
        return compound;
    }

    /**
     * Sets the value of the compound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompound(String value) {
        this.compound = value;
    }

    /**
     * Gets the value of the mwt property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMwt() {
        return mwt;
    }

    /**
     * Sets the value of the mwt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMwt(Float value) {
        this.mwt = value;
    }

    /**
     * Gets the value of the logp property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getLogp() {
        return logp;
    }

    /**
     * Sets the value of the logp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLogp(Float value) {
        this.logp = value;
    }

    /**
     * Gets the value of the desolvApolar property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDesolvApolar() {
        return desolvApolar;
    }

    /**
     * Sets the value of the desolvApolar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDesolvApolar(Float value) {
        this.desolvApolar = value;
    }

    /**
     * Gets the value of the desolvPolar property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDesolvPolar() {
        return desolvPolar;
    }

    /**
     * Sets the value of the desolvPolar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDesolvPolar(Float value) {
        this.desolvPolar = value;
    }

    /**
     * Gets the value of the hbd property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHbd() {
        return hbd;
    }

    /**
     * Sets the value of the hbd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHbd(Integer value) {
        this.hbd = value;
    }

    /**
     * Gets the value of the hba property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHba() {
        return hba;
    }

    /**
     * Sets the value of the hba property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHba(Integer value) {
        this.hba = value;
    }

    /**
     * Gets the value of the tpsa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTpsa() {
        return tpsa;
    }

    /**
     * Sets the value of the tpsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTpsa(Integer value) {
        this.tpsa = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCharge() {
        return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCharge(Integer value) {
        this.charge = value;
    }

    /**
     * Gets the value of the nrb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNrb() {
        return nrb;
    }

    /**
     * Sets the value of the nrb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNrb(Integer value) {
        this.nrb = value;
    }

    /**
     * Gets the value of the smiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmiles() {
        return smiles;
    }

    /**
     * Sets the value of the smiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmiles(String value) {
        this.smiles = value;
    }

}
