//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 03:58:49 PM EST 
//


package com.btechconsulting.wein.cumulus.model;

import javax.xml.bind.annotation.XmlRegistry;

import com.btechconsulting.wein.cumulus.model.NewCompound;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.btechconsulting.wein.cumulus.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.btechconsulting.wein.cumulus.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VinaParams }
     * 
     */
    public VinaParams createVinaParams() {
        return new VinaParams();
    }

    /**
     * Create an instance of {@link WorkUnit }
     * 
     */
    public WorkUnit createWorkUnit() {
        return new WorkUnit();
    }

    /**
     * Create an instance of {@link ReturnUnit }
     * 
     */
    public ReturnUnit createReturnUnit() {
        return new ReturnUnit();
    }

    /**
     * Create an instance of {@link NewCompound }
     * 
     */
    public NewCompound createNewCompound() {
        return new NewCompound();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link FilterParams }
     * 
     */
    public FilterParams createFilterParams() {
        return new FilterParams();
    }

}
