//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 03:58:49 PM EST 
//


package com.btechconsulting.wein.cumulus.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VinaParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VinaParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="center_x" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="center_y" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="center_z" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="size_x" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="size_y" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="size_z" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="exhaustiveness" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="seed" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="num_modes" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="energy_range" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VinaParams", propOrder = {
    "centerX",
    "centerY",
    "centerZ",
    "sizeX",
    "sizeY",
    "sizeZ",
    "exhaustiveness",
    "seed",
    "numModes",
    "energyRange"
})
@XmlRootElement
public class VinaParams {

    @XmlElement(name = "center_x")
    protected float centerX;
    @XmlElement(name = "center_y")
    protected float centerY;
    @XmlElement(name = "center_z")
    protected float centerZ;
    @XmlElement(name = "size_x")
    protected int sizeX;
    @XmlElement(name = "size_y")
    protected int sizeY;
    @XmlElement(name = "size_z")
    protected int sizeZ;
    protected Integer exhaustiveness;
    protected Integer seed;
    @XmlElement(name = "num_modes")
    protected Integer numModes;
    @XmlElement(name = "energy_range")
    protected Integer energyRange;

    /**
     * Gets the value of the centerX property.
     * 
     */
    public float getCenterX() {
        return centerX;
    }

    /**
     * Sets the value of the centerX property.
     * 
     */
    public void setCenterX(float value) {
        this.centerX = value;
    }

    /**
     * Gets the value of the centerY property.
     * 
     */
    public float getCenterY() {
        return centerY;
    }

    /**
     * Sets the value of the centerY property.
     * 
     */
    public void setCenterY(float value) {
        this.centerY = value;
    }

    /**
     * Gets the value of the centerZ property.
     * 
     */
    public float getCenterZ() {
        return centerZ;
    }

    /**
     * Sets the value of the centerZ property.
     * 
     */
    public void setCenterZ(float value) {
        this.centerZ = value;
    }

    /**
     * Gets the value of the sizeX property.
     * 
     */
    public int getSizeX() {
        return sizeX;
    }

    /**
     * Sets the value of the sizeX property.
     * 
     */
    public void setSizeX(int value) {
        this.sizeX = value;
    }

    /**
     * Gets the value of the sizeY property.
     * 
     */
    public int getSizeY() {
        return sizeY;
    }

    /**
     * Sets the value of the sizeY property.
     * 
     */
    public void setSizeY(int value) {
        this.sizeY = value;
    }

    /**
     * Gets the value of the sizeZ property.
     * 
     */
    public int getSizeZ() {
        return sizeZ;
    }

    /**
     * Sets the value of the sizeZ property.
     * 
     */
    public void setSizeZ(int value) {
        this.sizeZ = value;
    }

    /**
     * Gets the value of the exhaustiveness property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExhaustiveness() {
        return exhaustiveness;
    }

    /**
     * Sets the value of the exhaustiveness property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExhaustiveness(Integer value) {
        this.exhaustiveness = value;
    }

    /**
     * Gets the value of the seed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeed() {
        return seed;
    }

    /**
     * Sets the value of the seed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeed(Integer value) {
        this.seed = value;
    }

    /**
     * Gets the value of the numModes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumModes() {
        return numModes;
    }

    /**
     * Sets the value of the numModes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumModes(Integer value) {
        this.numModes = value;
    }

    /**
     * Gets the value of the energyRange property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEnergyRange() {
        return energyRange;
    }

    /**
     * Sets the value of the energyRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEnergyRange(Integer value) {
        this.energyRange = value;
    }

}
