//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.16 at 01:49:37 PM EST 
//


package com.btechconsulting.wein.cumulus.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilterParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="min_mwt" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="max_mwt" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="min_logp" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="max_logp" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="min_desolv_apolar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="max_desolv_apolar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="min_desolv_polar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="max_desolv_polar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="min_hbd" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="max_hbd" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="min_hba" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="max_hba" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="min_tpsa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="max_tpsa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="min_charge" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="max_charge" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="min_nrb" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="max_nrb" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="smiles" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="supplier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="min_suppliers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilterParams", propOrder = {
    "minMwt",
    "maxMwt",
    "minLogp",
    "maxLogp",
    "minDesolvApolar",
    "maxDesolvApolar",
    "minDesolvPolar",
    "maxDesolvPolar",
    "minHbd",
    "maxHbd",
    "minHba",
    "maxHba",
    "minTpsa",
    "maxTpsa",
    "minCharge",
    "maxCharge",
    "minNrb",
    "maxNrb",
    "smiles",
    "supplier",
    "minSuppliers"
})
@XmlRootElement
public class FilterParams {

    @XmlElement(name = "min_mwt")
    protected Float minMwt;
    @XmlElement(name = "max_mwt")
    protected Float maxMwt;
    @XmlElement(name = "min_logp")
    protected Float minLogp;
    @XmlElement(name = "max_logp")
    protected Float maxLogp;
    @XmlElement(name = "min_desolv_apolar")
    protected Float minDesolvApolar;
    @XmlElement(name = "max_desolv_apolar")
    protected Float maxDesolvApolar;
    @XmlElement(name = "min_desolv_polar")
    protected Float minDesolvPolar;
    @XmlElement(name = "max_desolv_polar")
    protected Float maxDesolvPolar;
    @XmlElement(name = "min_hbd")
    protected Integer minHbd;
    @XmlElement(name = "max_hbd")
    protected Integer maxHbd;
    @XmlElement(name = "min_hba")
    protected Integer minHba;
    @XmlElement(name = "max_hba")
    protected Integer maxHba;
    @XmlElement(name = "min_tpsa")
    protected Integer minTpsa;
    @XmlElement(name = "max_tpsa")
    protected Integer maxTpsa;
    @XmlElement(name = "min_charge")
    protected Integer minCharge;
    @XmlElement(name = "max_charge")
    protected Integer maxCharge;
    @XmlElement(name = "min_nrb")
    protected Integer minNrb;
    @XmlElement(name = "max_nrb")
    protected Integer maxNrb;
    protected String smiles;
    protected String supplier;
    @XmlElement(name = "min_suppliers")
    protected String minSuppliers;

    /**
     * Gets the value of the minMwt property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinMwt() {
        return minMwt;
    }

    /**
     * Sets the value of the minMwt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinMwt(Float value) {
        this.minMwt = value;
    }

    /**
     * Gets the value of the maxMwt property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaxMwt() {
        return maxMwt;
    }

    /**
     * Sets the value of the maxMwt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaxMwt(Float value) {
        this.maxMwt = value;
    }

    /**
     * Gets the value of the minLogp property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinLogp() {
        return minLogp;
    }

    /**
     * Sets the value of the minLogp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinLogp(Float value) {
        this.minLogp = value;
    }

    /**
     * Gets the value of the maxLogp property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaxLogp() {
        return maxLogp;
    }

    /**
     * Sets the value of the maxLogp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaxLogp(Float value) {
        this.maxLogp = value;
    }

    /**
     * Gets the value of the minDesolvApolar property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinDesolvApolar() {
        return minDesolvApolar;
    }

    /**
     * Sets the value of the minDesolvApolar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinDesolvApolar(Float value) {
        this.minDesolvApolar = value;
    }

    /**
     * Gets the value of the maxDesolvApolar property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaxDesolvApolar() {
        return maxDesolvApolar;
    }

    /**
     * Sets the value of the maxDesolvApolar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaxDesolvApolar(Float value) {
        this.maxDesolvApolar = value;
    }

    /**
     * Gets the value of the minDesolvPolar property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinDesolvPolar() {
        return minDesolvPolar;
    }

    /**
     * Sets the value of the minDesolvPolar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinDesolvPolar(Float value) {
        this.minDesolvPolar = value;
    }

    /**
     * Gets the value of the maxDesolvPolar property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaxDesolvPolar() {
        return maxDesolvPolar;
    }

    /**
     * Sets the value of the maxDesolvPolar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaxDesolvPolar(Float value) {
        this.maxDesolvPolar = value;
    }

    /**
     * Gets the value of the minHbd property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinHbd() {
        return minHbd;
    }

    /**
     * Sets the value of the minHbd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinHbd(Integer value) {
        this.minHbd = value;
    }

    /**
     * Gets the value of the maxHbd property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxHbd() {
        return maxHbd;
    }

    /**
     * Sets the value of the maxHbd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxHbd(Integer value) {
        this.maxHbd = value;
    }

    /**
     * Gets the value of the minHba property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinHba() {
        return minHba;
    }

    /**
     * Sets the value of the minHba property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinHba(Integer value) {
        this.minHba = value;
    }

    /**
     * Gets the value of the maxHba property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxHba() {
        return maxHba;
    }

    /**
     * Sets the value of the maxHba property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxHba(Integer value) {
        this.maxHba = value;
    }

    /**
     * Gets the value of the minTpsa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinTpsa() {
        return minTpsa;
    }

    /**
     * Sets the value of the minTpsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinTpsa(Integer value) {
        this.minTpsa = value;
    }

    /**
     * Gets the value of the maxTpsa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxTpsa() {
        return maxTpsa;
    }

    /**
     * Sets the value of the maxTpsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxTpsa(Integer value) {
        this.maxTpsa = value;
    }

    /**
     * Gets the value of the minCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinCharge() {
        return minCharge;
    }

    /**
     * Sets the value of the minCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinCharge(Integer value) {
        this.minCharge = value;
    }

    /**
     * Gets the value of the maxCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxCharge() {
        return maxCharge;
    }

    /**
     * Sets the value of the maxCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxCharge(Integer value) {
        this.maxCharge = value;
    }

    /**
     * Gets the value of the minNrb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinNrb() {
        return minNrb;
    }

    /**
     * Sets the value of the minNrb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinNrb(Integer value) {
        this.minNrb = value;
    }

    /**
     * Gets the value of the maxNrb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxNrb() {
        return maxNrb;
    }

    /**
     * Sets the value of the maxNrb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxNrb(Integer value) {
        this.maxNrb = value;
    }

    /**
     * Gets the value of the smiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmiles() {
        return smiles;
    }

    /**
     * Sets the value of the smiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmiles(String value) {
        this.smiles = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplier(String value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the minSuppliers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinSuppliers() {
        return minSuppliers;
    }

    /**
     * Sets the value of the minSuppliers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinSuppliers(String value) {
        this.minSuppliers = value;
    }

}
