//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 03:58:49 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/WorkUnit", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.btechconsulting.wein.nimbus.model;
